export const ADD_WORD_PAIR = 'ADD_TODO';
export const DELETE_WORD_PAIR = 'DELETE_WORD_PAIR';
export const EDIT_WORD_PAIR = 'EDIT_WORD_PAIR';
export const SAVE_EDIT = 'SAVE_EDIT';
export const ADD_DICTIONARY = 'ADD_DICTIONARY';
export const DELETE_DICTIONARY = 'DELETE_DICTIONARY';
export const EDIT_DICTIONARY = 'EDIT_DICTIONARY';
export const SAVE_DICTIONARY_EDIT = 'SAVE_DICTIONARY_EDIT';
